[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "personal_budget"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["python"]
include = ["personal_budget*"]